apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pdf-to-json
  name: pdf-to-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-to-json
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pdf-to-json
    spec:
      containers:
      - image: us.icr.io/samples/pdf-to-json:v1
        name: pdf-to-json
        resources: {}
status: {}
