apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pdf-to-json
  name: pdf-to-json
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pdf-to-json
  type: LoadBalancer
status:
  loadBalancer: {}
